"""empty message

Revision ID: 3ce75914ab63
Revises: 5a05524ae19d
Create Date: 2014-08-24 13:32:06.677740

"""

# revision identifiers, used by Alembic.
revision = '3ce75914ab63'
down_revision = '5a05524ae19d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
